<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <test thread-count="5" parallel="methods" name="Test(failed)" verbose="0">
    <classes>
      <class name="com.VtigerProject.LeadsTestCases.CreateLeadsWithValidCredentialsTest">
        <methods>
          <include name="setUp"/>
          <include name="tearUp"/>
          <include name="logout"/>
          <include name="CreateLeadsWithValidCredentialsTest1"/>
          <include name="loginApp"/>
        </methods>
      </class> <!-- com.VtigerProject.LeadsTestCases.CreateLeadsWithValidCredentialsTest -->
      <class name="com.VtigerProject.LeadsTestCases.CreateOrgAndCheckTest">
        <methods>
          <include name="setUp"/>
          <include name="createaOrgAndCheckInMemberIsPresntOrNot"/>
          <include name="tearUp"/>
          <include name="logout"/>
          <include name="loginApp"/>
        </methods>
      </class> <!-- com.VtigerProject.LeadsTestCases.CreateOrgAndCheckTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
